In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2, 3],
          [10, 20, 30]])

array([[ 1,  2,  3],
       [10, 20, 30]])

In [4]:
my_matrix = np.array([[1, 2, 3],
          [10, 20, 30]])

In [5]:
my_matrix.shape

(2, 3)

In [6]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [7]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [8]:
my_matrix.ndim

2

In [9]:
my_matrix * 2

array([[ 2,  4,  6],
       [20, 40, 60]])

In [10]:
my_matrix ** 2

array([[  1,   4,   9],
       [100, 400, 900]])

In [11]:
np.sin(my_matrix)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.54402111,  0.91294525, -0.98803162]])

In [12]:
other_matrix = np.array([[100, 500, 800],
                         [1000, 2000, 3000]])

In [14]:
other_matrix

array([[ 100,  500,  800],
       [1000, 2000, 3000]])

In [15]:
my_matrix * other_matrix

array([[  100,  1000,  2400],
       [10000, 40000, 90000]])

In [17]:
my_matrix @ other_matrix.T

array([[  3500,  14000],
       [ 35000, 140000]])

In [18]:
np.unique(my_matrix)

array([ 1,  2,  3, 10, 20, 30])